name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Test
      run: go test -v ./...
      
    - name: Build the Docker image 
      run: docker build -t jin06/goChat .
    
    - name: Login hub.docker.com
      run: docker login --username=${{ secrets.DOCKER_HUB_USER }} --password ${{ secrets.DOCKER_HUB_PASS }}
    - name: Push Image
      run: docker push jin06/goChat
